"use client";
import type {CSSProperties,ReactNode} from "react";
import {useMemo} from "react";
import Link from "next/link";
import {usePathname} from "next/navigation";
import GuestCommunicationsWorkspace from "@/components/staff/GuestCommunicationsWorkspace";
import GuestDirectCommunicationsWorkspace from "@/components/staff/GuestDirectCommunicationsWorkspace";
import StaffRoomActivityMap from "@/components/staff/StaffRoomActivityMap";
import {useStaffUi} from "@/components/staff/StaffUiProvider";
import type {StaffHotelBrand} from "@/lib/server/staff-hotel-brand";
import {staffText} from "@/lib/staff/ui-copy";
const ROLE_PATTERN=/^[a-z][a-z0-9_-]{0,62}$/;
export default function StaffHotelShell({hotelSlug,brand,children}:{hotelSlug:string;brand:StaffHotelBrand;children:ReactNode}){const pathname=usePathname();const{lang,setLang}=useStaffUi();const t=staffText(lang);const trainingLabel=lang==="bg"?"Обучение":lang==="de"?"Schulung":"Training";const role=useMemo(()=>{const parts=pathname.split("/").filter(Boolean);const candidate=parts[0]==="staff"&&parts[1]?String(parts[2]||"").toLowerCase():"";if(!candidate||candidate==="pin"||!ROLE_PATTERN.test(candidate))return null;return candidate},[pathname]);const style={"--staff-brand-primary":"#1479d3","--staff-brand-secondary":"#8f6dff","--staff-brand-accent":"#2c9dff","--staff-brand-background":"#f5faff","--staff-brand-soft":"#edf7ff","--staff-brand-surface":"#ffffff","--staff-on-brand":"#ffffff"} as CSSProperties;return <div className="stayhub-staff-shell gostaya-light-staff min-h-screen" data-staff-theme="light" data-brand-source="gostaya" style={style}><div className="stayhub-staff-brand-rail" aria-hidden="true"/><div className="mx-auto max-w-7xl px-4 py-4 sm:px-6 lg:px-8"><header className="stayhub-staff-topbar mb-5 overflow-hidden rounded-3xl border p-4 shadow-sm sm:p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="stayhub-staff-brand-dot" aria-hidden="true"/><p className="text-xs font-semibold uppercase tracking-[0.22em] opacity-70">GOSTAYA · STAFF</p></div><h1 className="mt-1 truncate text-xl font-semibold tracking-tight sm:text-2xl">{brand.hotelName}</h1><p className="mt-1 text-sm opacity-65">{t.simpleOperationalView}</p></div><div className="flex flex-wrap items-center gap-2">{role?<Link href={`/staff/${hotelSlug}/${role}/development`} className="stayhub-staff-select rounded-xl border px-3 py-2 text-sm font-semibold">{trainingLabel}</Link>:null}<select value={lang} onChange={e=>setLang(e.target.value as typeof lang)} className="stayhub-staff-select rounded-xl border px-3 py-2 text-sm outline-none" aria-label="Staff UI language"><option value="bg">BG</option><option value="en">EN</option><option value="de">DE</option></select></div></div></header><div className="stayhub-staff-workspace">{role?<GuestCommunicationsWorkspace hotelSlug={hotelSlug} role={role}/>:null}{role==="reception"?<GuestDirectCommunicationsWorkspace hotelSlug={hotelSlug} role={role}/>:null}{role==="reception"||role==="manager"?<StaffRoomActivityMap hotelSlug={hotelSlug} role={role}/>:null}{children}</div></div></div>}
