type Lang = "bg" | "en" | "de";

const COPY = {
  bg: { eyebrow:"LIVE HOTEL DEMO", title:"Сканирай като гост. После виж хотела отвътре.", text:"Отвори GOSTAYA на собствения си телефон, изпрати реална demo заявка и след това отвори Manager, за да видиш как същото действие се превръща в operational visibility.", scan:"Сканирай с телефона", scanNote:"QR води директно към изолирания GOSTAYA demo tenant.", cta:"Отвори Guest Hub", managerCta:"Отвори Manager след заявката", pin:"Demo PIN", room:"Demo стая", journey:"Една заявка през цялата система", safe:"Изолирана demo среда · demo/test записите не влизат в хотелски KPI.", steps:[["01","Guest","Сканирай QR и отвори Guest Hub"],["02","Request","Потвърди 901 и изпрати заявка"],["03","Operations","Виж routing и lifecycle в Staff Hub"],["04","Manager","Виж заявката, KPI и management modules"]], departments:"Оперативни панели", housekeeping:"Housekeeping", maintenance:"Maintenance", reception:"Reception", manager:"Manager" },
  en: { eyebrow:"LIVE HOTEL DEMO", title:"Scan as a guest. Then see the hotel from the inside.", text:"Open GOSTAYA on your own phone, send a real demo request, then open Manager to see how the same action becomes operational visibility.", scan:"Scan with your phone", scanNote:"The QR opens the isolated GOSTAYA demo tenant directly.", cta:"Open Guest Hub", managerCta:"Open Manager after your request", pin:"Demo PIN", room:"Demo room", journey:"One request across the whole system", safe:"Isolated demo environment · demo/test records are excluded from hotel KPI.", steps:[["01","Guest","Scan QR and open Guest Hub"],["02","Request","Confirm 901 and send a request"],["03","Operations","See routing and lifecycle in Staff Hub"],["04","Manager","See the request, KPI and management modules"]], departments:"Operational panels", housekeeping:"Housekeeping", maintenance:"Maintenance", reception:"Reception", manager:"Manager" },
  de: { eyebrow:"LIVE HOTEL DEMO", title:"Scanne als Gast. Sieh danach das Hotel von innen.", text:"Öffne GOSTAYA auf deinem eigenen Smartphone, sende eine echte Demo-Anfrage und öffne danach Manager, um zu sehen, wie dieselbe Aktion operative Transparenz erzeugt.", scan:"Mit dem Smartphone scannen", scanNote:"Der QR-Code öffnet direkt den isolierten GOSTAYA Demo-Tenant.", cta:"Guest Hub öffnen", managerCta:"Manager nach der Anfrage öffnen", pin:"Demo PIN", room:"Demo-Zimmer", journey:"Eine Anfrage durch das ganze System", safe:"Isolierte Demo-Umgebung · Demo/Test-Einträge werden nicht in Hotel-KPI gezählt.", steps:[["01","Gast","QR scannen und Guest Hub öffnen"],["02","Anfrage","901 bestätigen und Anfrage senden"],["03","Operations","Routing und Lifecycle im Staff Hub sehen"],["04","Manager","Anfrage, KPI und Management-Module sehen"]], departments:"Operative Panels", housekeeping:"Housekeeping", maintenance:"Technik", reception:"Rezeption", manager:"Manager" },
} satisfies Record<Lang, { eyebrow:string; title:string; text:string; scan:string; scanNote:string; cta:string; managerCta:string; pin:string; room:string; journey:string; safe:string; steps:string[][]; departments:string; housekeeping:string; maintenance:string; reception:string; manager:string }>;

function DemoQr() {
  const src = "https://api.qrserver.com/v1/create-qr-code/?size=240x240&margin=10&data=https%3A%2F%2Fgostaya.com%2Fh%2Fdemo";
  return <div className="rounded-[26px] bg-white p-3 shadow-2xl"><img src={src} width="216" height="216" loading="lazy" alt="QR code to open the GOSTAYA live demo Guest Hub" className="h-auto w-full" /></div>;
}

export default function DemoSpotlight({ lang }: { lang: Lang }) {
  const c = COPY[lang];
  return (
    <section id="demo" className="relative overflow-hidden border-y border-white/10">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_22%_45%,rgba(34,211,238,.22),transparent_34%),radial-gradient(circle_at_80%_30%,rgba(167,139,250,.18),transparent_30%),linear-gradient(180deg,rgba(255,255,255,.025),transparent)]" />
      <div className="relative mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:py-24">
        <div className="rounded-[38px] border border-cyan-200/20 bg-gradient-to-br from-white/[0.09] via-white/[0.04] to-cyan-300/[0.06] p-6 shadow-[0_0_80px_rgba(34,211,238,.08)] backdrop-blur-xl sm:p-9">
          <div className="grid gap-8 lg:grid-cols-[1fr_.85fr] lg:items-center">
            <div><p className="text-xs font-black uppercase tracking-[0.25em] text-cyan-200">{c.eyebrow}</p><h2 className="mt-4 max-w-3xl text-3xl font-semibold tracking-tight text-white sm:text-5xl">{c.title}</h2><p className="mt-4 max-w-2xl text-base leading-7 text-slate-200">{c.text}</p>
              <div className="mt-6 flex flex-wrap gap-3"><a href="/h/demo" target="_blank" rel="noreferrer" className="rounded-2xl bg-cyan-200 px-5 py-3 text-sm font-black text-slate-950 transition hover:-translate-y-0.5 hover:bg-white">{c.cta}</a><a href="/staff/demo/manager" target="_blank" rel="noreferrer" className="rounded-2xl border border-violet-200/25 bg-violet-200/[0.08] px-5 py-3 text-sm font-bold text-violet-50">{c.managerCta}</a></div><p className="mt-4 text-xs leading-5 text-white/45">{c.safe}</p>
            </div>
            <div className="grid gap-4 sm:grid-cols-[.8fr_1fr] sm:items-center"><div><DemoQr /><div className="mt-3 text-center text-sm font-bold text-white">{c.scan}</div><div className="mt-1 text-center text-xs leading-5 text-white/40">{c.scanNote}</div></div><div className="space-y-3"><div className="rounded-3xl border border-cyan-200/20 bg-cyan-200/[0.07] p-5"><div className="text-xs uppercase tracking-widest text-cyan-100/60">{c.pin}</div><div className="mt-1 text-4xl font-black tracking-[.16em]">2026</div></div><div className="rounded-3xl border border-violet-200/20 bg-violet-200/[0.07] p-5"><div className="text-xs uppercase tracking-widest text-violet-100/60">{c.room}</div><div className="mt-1 text-4xl font-black">901</div></div></div></div>
          </div>
          <div className="mt-9 border-t border-white/10 pt-7"><div className="text-xs font-black uppercase tracking-[0.22em] text-white/40">{c.journey}</div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{c.steps.map(([n,title,detail])=><div key={n} className="rounded-2xl border border-white/10 bg-black/15 p-4"><div className="text-[10px] font-black text-cyan-200">{n}</div><div className="mt-2 text-sm font-bold">{title}</div><div className="mt-1 text-xs leading-5 text-white/50">{detail}</div></div>)}</div>
            <div className="mt-5 flex flex-col gap-3 rounded-2xl border border-white/10 bg-white/[0.035] p-4 lg:flex-row lg:items-center lg:justify-between"><div className="text-sm font-semibold">{c.departments} · PIN 2026</div><div className="flex flex-wrap gap-2"><a href="/staff/demo/housekeeping" target="_blank" rel="noreferrer" className="rounded-xl border border-white/10 bg-white/[0.06] px-3 py-2 text-xs font-semibold">{c.housekeeping}</a><a href="/staff/demo/maintenance" target="_blank" rel="noreferrer" className="rounded-xl border border-white/10 bg-white/[0.06] px-3 py-2 text-xs font-semibold">{c.maintenance}</a><a href="/staff/demo/reception" target="_blank" rel="noreferrer" className="rounded-xl border border-white/10 bg-white/[0.06] px-3 py-2 text-xs font-semibold">{c.reception}</a><a href="/staff/demo/manager" target="_blank" rel="noreferrer" className="rounded-xl border border-violet-200/20 bg-violet-200/[0.08] px-3 py-2 text-xs font-semibold text-violet-100">{c.manager}</a></div></div>
          </div>
        </div>
      </div>
    </section>
  );
}
