export type DemoGuideAction = "guest" | "room" | "department" | "manager" | "housekeeping" | "reception" | "survey" | "checkout" | "previous" | "next" | "restart" | "hide" | "show";
export type DemoGuideModel = {
  step: number; total: number; title: string; instructions: readonly string[]; expected: string;
  actions: readonly DemoGuideAction[]; canContinue: boolean; hidden: boolean; finished: boolean; busy: boolean; request?: {id:string;status:string};
};
export const DEMO_GUIDE_CHANNEL = "gostaya-demo-guide-v4";
export const DEMO_GUIDE_ACTIONS: readonly DemoGuideAction[] = ["guest", "room", "department", "manager", "housekeeping", "reception", "survey", "checkout", "previous", "next", "restart", "hide", "show"];

type Step = { title: string; instructions: readonly string[]; expected: string; actions: readonly DemoGuideAction[] };
export const DEMO_GUIDE_STEPS: Record<"bg" | "en" | "de", readonly Step[]> = {
  bg: [
    {title:"Потвърдете демо стаята", instructions:["В портала за госта въведете 901 в полето за стая.", "Натиснете бутона за потвърждение. Ако се покаже второ потвърждение или приветствие, завършете го."], expected:"Стая 901 е потвърдена и услугите в хъба са отключени. Продължете, когато виждате този резултат.", actions:["room"]},
    {title:"Отворете Онлайн хаускипинг", instructions:["В портала за госта изберете „Онлайн хаускипинг“ или използвайте бутона по-долу.", "Намерете услугата „Хавлии“. На този етап само разглеждате — още няма изпратена заявка."], expected:"Отворени са услугите на Хаускипинг. Следващата стъпка ще изпрати конкретна тестова заявка.", actions:["department"]},
    {title:"Изпратете заявка за хавлии", instructions:["Изберете „Хавлии“. Ако се показват количество или вид, изберете нужната опция.", "Потвърдете изпращането и изчакайте съобщението за успешно приета заявка.", "Запомнете часа на заявката, за да я различите от други тестове за стая 901."], expected:"Заявката вече е записана и насочена към отдела. Тя е TEST и не влиза в реалните хотелски KPI.", actions:["department"]},
    {title:"Намерете същата заявка при мениджъра", instructions:["Натиснете „Отворете Мениджър“. Панелът се показва вдясно от насоките.", "В активните заявки намерете стая 901, услугата „Хавлии“ и часа от предишната стъпка.", "Проверете отдела и текущия статус. При нужда изчакайте обновяването на списъка."], expected:"Мениджърът вижда същата заявка, без рецепцията да я преписва или предава по телефона.", actions:["manager"]},
    {title:"Обработете заявката в отговорния отдел", instructions:["Отворете Хаускипинг. Извън работното му време активната заявка се поема от Рецепция — ако не я виждате тук, отворете Рецепция. Демо PIN: 2026.", "Намерете вашата заявка за стая 901 и натиснете „СТАРТ“. Статусът става „В процес“.", "Натиснете „ГОТОВО“, за да симулирате изпълнението. Това е действие в тестовата среда."], expected:"След „СТАРТ“ отделът поема задачата. След „ГОТОВО“ изпълнението се записва и заявката излиза от активната опашка.", actions:["housekeeping", "reception"]},
    {title:"Сравнете резултата за госта и мениджъра", instructions:["Върнете се в портала за госта. По време на изпълнението заявката е „В обработка“, а след „ГОТОВО“ остава като „Изпълнена“ за 12 секунди след отварянето на хъба.", "Отворете отново Мениджър. Проверете активните и приключените заявки за стая 901.", "Продължете, след като сравните двата изгледа — преминаването напред само по себе си не изпълнява заявка."], expected:"Гостът получава обратна връзка, а мениджърът проследява приключената работа. Всички виждат един и същ процес.", actions:["guest","manager"]},
    {title:"Разгледайте лично съобщение до гост", instructions:["Отворете Рецепция → „Лични съобщения“ и изберете стая 901.", "За тест можете да напишете „Хавлиите са доставени. Приятен престой!“ и да го изпратите.", "Върнете се в портала за госта и проверете входящите съобщения."], expected:"Личното съобщение е адресирано към избраната стая. Тази стъпка е по желание; можете да продължите и без изпращане.", actions:["reception"]},
    {title:"Разгледайте съобщение до всички гости", instructions:["В Рецепция отворете „Общи съобщения“.", "За тест можете да създадете съобщение „Демо: вечерната програма започва в 20:00“ и да го публикувате.", "Проверете съобщението в портала за госта. Демо съобщенията остават в демо хъба."], expected:"Виждате разликата между лично съобщение и обща хотелска комуникация. Изпращането тук е по желание.", actions:["reception"]},
    {title:"Разгледайте анкетата за престоя", instructions:["Натиснете „Покажете анкетата“, за да я отворите за демо стая 901.", "Разгледайте въпросите. Ако желаете, попълнете тестова обратна връзка.", "Затворете анкетата и продължете към последната стъпка."], expected:"Хотелът може да събира обратна връзка по време на престоя. Отварянето на анкетата не означава, че е изпратен отговор.", actions:["survey"]},
    {title:"Приключете тестовия престой", instructions:["След като приключите прегледа, натиснете „Приключете престоя“.", "Това симулира checkout за демо стая 901 и връща гостовия хъб към началния екран."], expected:"Достъпът за текущия демо престой приключва. Можете да започнете отначало с ново потвърждение на стаята.", actions:["checkout"]},
  ],
  en: [
    {title:"Confirm the demo room", instructions:["Enter 901 in the Guest Hub room field.","Confirm the room and finish any confirmation or welcome dialog."], expected:"Room 901 is confirmed and services are unlocked. Continue once you see this result.",actions:["room"]},
    {title:"Open Online Housekeeping",instructions:["Choose Online Housekeeping in the Guest Hub, or use the button below.","Find Towels. You are only browsing; no request has been sent yet."],expected:"Housekeeping services are open. The next step will send a specific test request.",actions:["department"]},
    {title:"Send a request for towels",instructions:["Choose Towels and select a quantity or type if asked.","Confirm submission and wait for the success message.","Note the request time to distinguish it from other room 901 tests."],expected:"The request is saved and routed to the department. It is TEST and excluded from real hotel KPIs.",actions:["department"]},
    {title:"Find the same request in Manager",instructions:["Select Open Manager. The panel appears to the right of this guide.","In active requests, find room 901, Towels and the time you noted.","Check the department and status. Allow the list to refresh if needed."],expected:"The manager sees the same request without reception having to relay it.",actions:["manager"]},
    {title:"Process it in the responsible department",instructions:["Open Housekeeping. Outside its working hours, Reception covers active requests; if you do not see yours here, open Reception. Demo PIN: 2026.","Find your room 901 request and select START. Its status changes to In Progress.","Select DONE to simulate completion in the test environment."],expected:"START assigns the work. DONE records completion and removes it from the active queue.",actions:["housekeeping", "reception"]},
    {title:"Compare the guest and manager results",instructions:["Return to the Guest Hub. During processing the request shows In progress; after DONE it remains Completed for 12 seconds after the hub opens.","Open Manager again and check active and completed requests for room 901.","Compare both views before continuing; advancing the guide does not complete a request."],expected:"The guest receives feedback and the manager can follow the completed work.",actions:["guest","manager"]},
    {title:"Explore a personal guest message",instructions:["Open Reception → Personal messages and choose room 901.","Optionally send: Your towels have been delivered. Enjoy your stay!","Return to the Guest Hub inbox and check the message."],expected:"A personal message goes to the selected room. Sending is optional in this step.",actions:["reception"]},
    {title:"Explore a message to all guests",instructions:["In Reception, open Guest broadcasts.","Optionally publish: Demo: the evening programme starts at 20:00.","Check it in the Guest Hub. Demo messages stay within the demo hub."],expected:"See the difference between a private message and a hotel broadcast. Sending is optional.",actions:["reception"]},
    {title:"Explore the stay survey",instructions:["Select Show survey to open it for demo room 901.","Review the questions and optionally submit test feedback.","Close the survey and continue to the last step."],expected:"The hotel can collect feedback during a stay. Opening the survey does not submit a response.",actions:["survey"]},
    {title:"End the test stay",instructions:["When finished, select End stay.","This simulates checkout for demo room 901 and returns the Guest Hub to its start screen."],expected:"Access for this demo stay ends. You can start again by confirming the room.",actions:["checkout"]},
  ],
  de: [
    {title:"Demo-Zimmer bestätigen",instructions:["Geben Sie im Guest Hub die Zimmernummer 901 ein.","Bestätigen Sie das Zimmer und schließen Sie weitere Bestätigungs- oder Willkommensdialoge ab."],expected:"Zimmer 901 ist bestätigt und die Services sind freigeschaltet. Fahren Sie dann fort.",actions:["room"]},
    {title:"Online-Housekeeping öffnen",instructions:["Wählen Sie Online-Housekeeping im Guest Hub oder die Schaltfläche unten.","Suchen Sie Handtücher. Bisher wird noch keine Anfrage gesendet."],expected:"Die Housekeeping-Services sind geöffnet. Im nächsten Schritt senden Sie eine Testanfrage.",actions:["department"]},
    {title:"Handtücher anfordern",instructions:["Wählen Sie Handtücher und bei Bedarf Menge oder Art.","Bestätigen Sie das Senden und warten Sie auf die Erfolgsmeldung.","Merken Sie sich die Uhrzeit, um Ihre Anfrage von anderen Tests für Zimmer 901 zu unterscheiden."],expected:"Die Anfrage ist gespeichert und weitergeleitet. Sie ist TEST und zählt nicht zu echten Hotel-KPI.",actions:["department"]},
    {title:"Dieselbe Anfrage im Manager finden",instructions:["Wählen Sie Manager öffnen. Der Bereich erscheint rechts neben dieser Anleitung.","Suchen Sie unter aktiven Anfragen Zimmer 901, Handtücher und die notierte Uhrzeit.","Prüfen Sie Abteilung und Status. Warten Sie bei Bedarf auf die Aktualisierung."],expected:"Der Manager sieht dieselbe Anfrage, ohne dass die Rezeption sie weitergeben muss.",actions:["manager"]},
    {title:"In der zuständigen Abteilung bearbeiten",instructions:["Öffnen Sie Housekeeping. Außerhalb der Dienstzeit übernimmt die Rezeption aktive Anfragen. Wenn Ihre Anfrage hier fehlt, öffnen Sie die Rezeption. Demo-PIN: 2026.","Suchen Sie Ihre Anfrage für Zimmer 901 und wählen Sie START. Der Status wird In Bearbeitung.","Wählen Sie ERLEDIGT, um die Erledigung in der Testumgebung zu simulieren."],expected:"START übernimmt die Aufgabe. ERLEDIGT dokumentiert den Abschluss und entfernt sie aus der aktiven Liste.",actions:["housekeeping", "reception"]},
    {title:"Ergebnis für Gast und Manager vergleichen",instructions:["Prüfen Sie den Guest Hub: Während der Bearbeitung ist der Status aktualisiert; nach ERLEDIGT verschwindet die Anfrage aus der aktiven Liste.","Öffnen Sie erneut Manager und vergleichen Sie aktive und erledigte Anfragen für Zimmer 901.","Erst nach dem Vergleich weitergehen; der nächste Anleitungsschritt erledigt keine Anfrage."],expected:"Der Gast erhält Rückmeldung und der Manager kann die erledigte Arbeit verfolgen.",actions:["guest","manager"]},
    {title:"Persönliche Nachricht ansehen",instructions:["Öffnen Sie Rezeption → Persönliche Nachrichten und wählen Sie Zimmer 901.","Optional senden: Ihre Handtücher wurden geliefert. Einen schönen Aufenthalt!","Prüfen Sie die Nachricht im Posteingang des Guest Hubs."],expected:"Die Nachricht richtet sich an das gewählte Zimmer. Das Senden ist hier optional.",actions:["reception"]},
    {title:"Nachricht an alle Gäste ansehen",instructions:["Öffnen Sie in der Rezeption die Gäste-Broadcasts.","Optional veröffentlichen: Demo: Das Abendprogramm beginnt um 20:00 Uhr.","Prüfen Sie die Nachricht im Guest Hub. Demo-Nachrichten bleiben im Demo-Hub."],expected:"So unterscheiden sich persönliche und allgemeine Hotelnachrichten. Das Senden ist optional.",actions:["reception"]},
    {title:"Umfrage zum Aufenthalt ansehen",instructions:["Wählen Sie Umfrage anzeigen für Demo-Zimmer 901.","Prüfen Sie die Fragen und senden Sie optional Testfeedback.","Schließen Sie die Umfrage und fahren Sie fort."],expected:"Das Hotel kann Feedback während des Aufenthalts sammeln. Öffnen allein sendet keine Antwort.",actions:["survey"]},
    {title:"Testaufenthalt beenden",instructions:["Wählen Sie zum Abschluss Aufenthalt beenden.","Dies simuliert den Checkout für Demo-Zimmer 901 und setzt den Guest Hub zurück."],expected:"Der Zugang für den Demo-Aufenthalt endet. Sie können das Zimmer erneut bestätigen.",actions:["checkout"]},
  ],
};

export const DEMO_SHORT_GUIDE: Record<"bg"|"en"|"de", readonly string[]> = {
 bg:["Въведете 901 и потвърдете стаята.","Отворете Онлайн хаускипинг → Хавлии.","Изберете хавлии и потвърдете заявката.","Вижте същата заявка за стая 901 при мениджъра.","В посочения отдел натиснете СТАРТ, после ГОТОВО.","В хъба вижте статуса. Готовата заявка остава видима 12 секунди.","Рецепция → Лични съобщения → стая 901.","Рецепция → Общи съобщения.","Отворете анкетата за престоя.","Приключете тестовия престой."],
 en:["Enter 901 and confirm the room.","Open Online Housekeeping → Towels.","Choose towels and confirm the request.","Find the same room 901 request in Manager.","In the indicated department select START, then DONE.","Check the status in the hub. Completion stays visible for 12 seconds.","Reception → Personal messages → room 901.","Reception → Broadcasts.","Open the stay survey.","End the test stay."],
 de:["901 eingeben und Zimmer bestätigen.","Online-Housekeeping → Handtücher öffnen.","Handtücher wählen und Anfrage bestätigen.","Dieselbe Anfrage für Zimmer 901 im Manager ansehen.","Im angezeigten Bereich START und dann ERLEDIGT wählen.","Status im Hub prüfen. Erledigung bleibt 12 Sekunden sichtbar.","Rezeption → Persönliche Nachrichten → Zimmer 901.","Rezeption → Mitteilungen.","Umfrage öffnen.","Testaufenthalt beenden."]
};
