import type {
  StaffDepartment,
  StaffRequestStatus,
  StaffRequestType,
  StaffServiceTime,
} from "@/lib/staff/types";
import type { StaffUiLang } from "@/components/staff/StaffUiProvider";

const copy = {
  bg: {
    guestHub: "GuestHub",
    staffHub: "Служебен център",
    simpleOperationalView: "Изчистен оперативен изглед за хотелския екип",
    department: "Отдел",
    housekeeping: "Камериерки",
    maintenance: "Техническа поддръжка",
    reception: "Рецепция",
    restaurant: "Ресторант",
    managerDashboard: "Мениджърски контролен панел",
    staffHubModules: "Модули за служители",
    staffHubIntro:
      "Това е вътрешната част на GuestHub за служители. Интерфейсът е умишлено изчистен: ясни списъци със задачи, четими карти и бързи действия.",
    housekeepingDesc:
      "Общи заявки от гости като хавлии, тоалетна хартия, възглавници, одеяла, ютия и минибар.",
    maintenanceDesc:
      "Технически проблеми като климатик, топла вода, осветление и други неизправности.",
    receptionDesc:
      "Наблюдение на всички заявки по отдели, плюс обработка на заявките за рецепция.",
    managerDesc:
      "Пълен оперативен преглед по отдели, статуси и натоварване.",
    departmentBadge: "Отдел",
    controlBadge: "Контрол",
    managementBadge: "Управление",
    openArrow: "Отвори →",
    confirmedProductDecisions: "Потвърдени продуктови решения",
    confirmedDecision1:
      "Заявките от гости включват само допълнителни услуги и по избор заявки, не стандартно почистване на стая.",
    confirmedDecision2:
      "Задължителни хотелски операции като room cleaning не са част от guest request потока.",
    confirmedDecision3:
      "Рецепцията следи всички заявки, а отделите работят по своите собствени заявки.",
    confirmedDecision4: "Потокът за служители е максимално прост: Старт, Завършено, Върни.",
    sharedHousekeepingBoard: "Общ board за камериерки",
    unlockSupervisorActions: "Отключи действията на супервайзъра",
    lockSupervisorMode: "Заключи супервайзър режим",
    supervisorPinRequired: "Нужен е PIN на супервайзъра за промяна на housekeeping заявки.",
    incorrectPin: "Грешен PIN.",
    housekeepingIntro:
      "Общ supervisory board само за допълнителни guest заявки. Няма стандартен workflow за room cleaning тук.",
    maintenanceIntro:
      "Само технически guest проблеми. Ясен номер на стая, ясен проблем и бързи статус действия.",
    receptionIntro:
      "Оперативен контролен изглед. Рецепцията изпълнява само своите заявки и следи останалите отдели в режим само за преглед.",
    managerIntro:
      "Пълен оперативен преглед за всички отдели. Фокус върху активното натоварване, върнатите заявки и най-старите нерешени задачи.",
    controlCenterMonitoring: "Контролен център + наблюдение",
    technicalQueue: "Активна техническа опашка",
    allDepartmentsOverview: "Пълен преглед на всички отдели",
    total: "Общо",
    active: "Активни",
    new: "Нови",
    inProgress: "В процес",
    completed: "Приключени",
    returned: "Върнати",
    receptionOpen: "Отворени за рецепция",
    otherDepartmentsOpen: "Отворени в други отдели",
    activeOnly: "Активни + върнати",
    receptionActions: "Действия на рецепция",
    receptionActionsText: "Тези заявки могат да бъдат обработени директно от рецепция.",
    monitoringOnly: "Само наблюдение",
    monitoringOnlyText:
      "Рецепцията може да следи тези заявки, но изпълнението остава в съответния отдел.",
    noReceptionRequests: "Няма заявки за рецепция по текущия филтър.",
    noMonitoringRequests: "Няма заявки за наблюдение по текущия филтър.",
    oldestActiveRequests: "Най-стари активни заявки",
    oldestActiveRequestsText: "Тези нерешени заявки чакат най-дълго.",
    noActiveRequests: "В момента няма активни заявки.",
    filteredRequestView: "Филтриран изглед на заявките",
    filteredRequestViewText: "Преглед по отдели и статуси за оперативно проследяване.",
    noRequestsForFilter: "Няма заявки по текущия филтър.",
    departmentFilter: "Филтър по отдел",
    statusFilter: "Филтър по статус",
    sort: "Подредба",
    priority: "Приоритет",
    newest: "Най-нови",
    oldest: "Най-стари",
    all: "Всички",
    activeSummaryOnly: "Показват се само активните и върнатите заявки за отдела.",
    allStaffCanMonitor: "Всички камериерки могат да следят новите заявки. Смяна на статус изисква PIN на супервайзъра.",
    room: "Стая",
    date: "Дата",
    time: "Час",
    status: "Статус",
    requestedAt: "Подадена в",
    serviceTimeNow: "Сега",
    serviceTimeTomorrow: "Утре",
    serviceTimeToday: "Днес",
    managerViewOnly: "Само за преглед от мениджър. Пълна видимост по всички отдели.",
    receptionMonitoringOnly: "Само наблюдение от рецепция. Изпълнението е в съответния отдел.",
    start: "СТАРТ",
    done: "ГОТОВО",
    return: "ВЪРНИ",
    noActionsAvailable: "Няма налични действия",
    reports: "Отчети",
    reportsIntro:
      "Управленският изглед показва кои типове заявки се повтарят най-често и кои стаи генерират най-много проблеми.",
    reportSnapshot: "Бърз отчет",
    topRequestTypes: "Най-чести типове заявки",
    problematicRooms: "Най-проблемни стаи",
    problematicRoomsText: "Стаите с най-много заявки, активни случаи и върнати проблеми.",
    roomIssueBreakdown: "Разбивка по стая",
    roomIssueBreakdownText: "Показва кои проблеми се повтарят в една и съща стая.",
    requestCount: "Брой",
    returnedIssues: "Върнати проблеми",
    openIssues: "Отворени проблеми",
    topIssue: "Най-чест проблем",
    problemRoom: "Най-проблемна стая",
    problemRequests: "Проблемни заявки",
    activeRooms: "Стаи с активни проблеми",
    noReportData: "Все още няма достатъчно данни за отчетите.",
    noProblemData: "Няма налични данни за проблеми.",
    noRequestData: "Няма налични данни за заявки.",
    issueMix: "Най-чести проблеми в тази стая",
    reportsCompactLabel: "Организирани отчети",
    reportsCompactIntro: "Избери отделен отчет за всички заявки или само за техническите проблеми и го свали като CSV или Excel файл.",
    requestsSnapshot: "Заявки: бърз отчет",
    requestHeavyRooms: "Стаи с най-много заявки",
    problemsSnapshot: "Проблеми: бърз отчет",
    topProblemTypes: "Най-чести проблеми",
    openRequests: "Отворени заявки",
    returnedRequests: "Върнати заявки",
    openRequestsText: "Заявки, които още не са приключени.",
    returnedRequestsText: "Заявки, върнати за повторна обработка.",
    openIssuesText: "Технически проблеми, които още не са приключени.",
    returnedIssuesText: "Технически проблеми, върнати за повторна обработка.",
    requestHeavyRoom: "Стая с най-много заявки",
    requestHeavyRoomCount: "Брой за стаята с най-много заявки",
    roomsWithOpenRequests: "Стаи с отворени заявки",
    topRequest: "Най-честа заявка",
    topRequestTypesText: "Тези типове заявки се повтарят най-често, независимо от отдела.",
    problemTypesText: "Тези технически проблеми се повтарят най-често и изискват намеса от техник.",
    requestRoomsText: "Стаите с най-много заявки общо, не само технически проблеми.",
    problemRoomText: "Стаите с най-много технически проблеми, които изискват намеса от техник.",
    problemType: "Тип проблем",
    exportCsv: "Свали CSV",
    exportExcel: "Свали Excel",
    metric: "Показател",
    value: "Стойност",
    requestType: "Тип заявка",
    topIssueCount: "Брой за най-чест проблем",
    problemRoomCount: "Брой за най-проблемна стая",
    totalRequests: "Общо заявки",
    totalIssues: "Общо проблеми",
    completedRequests: "Приключени заявки",
    completedIssues: "Приключени проблеми",
    reportDetails: "Детайл по отчета",
    reportDetailsIntro: "Кликни върху карта, ред или показател, за да се отвори подробният списък отдолу.",
    reportDetailsEmpty: "Няма елементи за този детайл по отчета.",
    closeDetails: "Затвори детайла",
    soundAlertsLabel: "Звук за нови заявки",
    alertSoundOn: "Звукът е включен",
    alertSoundOff: "Звукът е изключен",
  },
  en: {
    guestHub: "GuestHub",
    staffHub: "Staff Hub",
    simpleOperationalView: "Simple operational view for hotel staff",
    department: "Department",
    housekeeping: "Housekeeping",
    maintenance: "Maintenance",
    reception: "Reception",
    restaurant: "Restaurant",
    managerDashboard: "Manager Dashboard",
    staffHubModules: "Staff Hub Modules",
    staffHubIntro:
      "This is the internal GuestHub side for staff. The interface is intentionally simple: clear task lists, readable cards and fast actions.",
    housekeepingDesc:
      "Shared guest supply requests like towels, toilet paper, pillows, blankets, iron and minibar refill.",
    maintenanceDesc:
      "Technical issues such as air conditioning, hot water, lights and other defects.",
    receptionDesc:
      "Monitor all department requests and execute reception-owned requests.",
    managerDesc:
      "Full operational overview across departments, statuses and workload.",
    departmentBadge: "Department",
    controlBadge: "Control",
    managementBadge: "Management",
    openArrow: "Open →",
    confirmedProductDecisions: "Confirmed product decisions",
    confirmedDecision1:
      "Guest requests include only optional services and optional requests, not standard room cleaning.",
    confirmedDecision2:
      "Mandatory hotel operations like room cleaning are not part of the guest request flow.",
    confirmedDecision3:
      "Reception monitors all requests, while departments work on their own tasks.",
    confirmedDecision4: "The staff flow stays simple: Start, Done, Return.",
    sharedHousekeepingBoard: "Shared housekeeping board",
    unlockSupervisorActions: "Unlock supervisor actions",
    lockSupervisorMode: "Lock supervisor mode",
    supervisorPinRequired: "Supervisor PIN required to update housekeeping requests.",
    incorrectPin: "Incorrect PIN.",
    housekeepingIntro:
      "Shared supervisor board for optional guest requests only. No standard room cleaning workflow here.",
    maintenanceIntro:
      "Technical guest issues only. Clear room number, clear problem type and simple status actions.",
    receptionIntro:
      "Operational control view. Reception executes only reception tasks and monitors the other departments in read-only mode.",
    managerIntro:
      "Full operational overview across all departments. Focus on active load, returned requests and the oldest unresolved items.",
    controlCenterMonitoring: "Control center + monitoring",
    technicalQueue: "Active technical queue",
    allDepartmentsOverview: "All departments overview",
    total: "Total",
    active: "Active",
    new: "New",
    inProgress: "In Progress",
    completed: "Completed",
    returned: "Returned",
    receptionOpen: "Reception Open",
    otherDepartmentsOpen: "Other Departments Open",
    activeOnly: "Active + returned",
    receptionActions: "Reception actions",
    receptionActionsText: "These requests can be handled directly by reception.",
    monitoringOnly: "Monitoring only",
    monitoringOnlyText:
      "Reception can monitor these requests, but execution stays inside the assigned department.",
    noReceptionRequests: "No reception requests in the current filter.",
    noMonitoringRequests: "No monitoring requests in the current filter.",
    oldestActiveRequests: "Oldest active requests",
    oldestActiveRequestsText: "These unresolved items have been waiting the longest.",
    noActiveRequests: "No active requests at the moment.",
    filteredRequestView: "Filtered request view",
    filteredRequestViewText: "Cross-department visibility for operational follow-up.",
    noRequestsForFilter: "No requests match the current filter.",
    departmentFilter: "Department filter",
    statusFilter: "Status filter",
    sort: "Sort",
    priority: "Priority",
    newest: "Newest",
    oldest: "Oldest",
    all: "All",
    activeSummaryOnly: "Only active and returned requests are shown for this department.",
    allStaffCanMonitor: "All housekeeping staff can monitor incoming requests. Status changes require supervisor PIN.",
    room: "Room",
    date: "Date",
    time: "Time",
    status: "Status",
    requestedAt: "Requested at",
    serviceTimeNow: "Now",
    serviceTimeTomorrow: "Tomorrow",
    serviceTimeToday: "Today",
    managerViewOnly: "Manager view only. Operational visibility across all departments.",
    receptionMonitoringOnly: "Reception monitoring only. Execution happens inside the assigned department.",
    start: "START",
    done: "DONE",
    return: "RETURN",
    noActionsAvailable: "No actions available",
    reports: "Reports",
    reportsIntro:
      "The management view shows which request types repeat most often and which rooms generate the most issues.",
    reportSnapshot: "Quick snapshot",
    topRequestTypes: "Top request types",
    problematicRooms: "Most problematic rooms",
    problematicRoomsText: "Rooms with the highest request volume, open cases and returned issues.",
    roomIssueBreakdown: "Room issue breakdown",
    roomIssueBreakdownText: "Shows which issues repeat in the same room.",
    requestCount: "Count",
    returnedIssues: "Returned issues",
    openIssues: "Open issues",
    topIssue: "Top issue",
    problemRoom: "Most problematic room",
    problemRequests: "Problem requests",
    activeRooms: "Rooms with open issues",
    noReportData: "There is not enough data for reports yet.",
    noProblemData: "No problem data available.",
    noRequestData: "No request data available.",
    issueMix: "Most frequent issues in this room",
    reportsCompactLabel: "Organized reports",
    reportsCompactIntro: "Choose a separate report for all requests or only for technical problems and download it as CSV or Excel.",
    requestsSnapshot: "Requests: quick snapshot",
    requestHeavyRooms: "Rooms with most requests",
    problemsSnapshot: "Problems: quick snapshot",
    topProblemTypes: "Top problem types",
    openRequests: "Open requests",
    returnedRequests: "Returned requests",
    openRequestsText: "Requests that are still not completed.",
    returnedRequestsText: "Requests sent back for another handling cycle.",
    openIssuesText: "Technical problems that are still not completed.",
    returnedIssuesText: "Technical problems sent back for another handling cycle.",
    requestHeavyRoom: "Room with most requests",
    requestHeavyRoomCount: "Count for room with most requests",
    roomsWithOpenRequests: "Rooms with open requests",
    topRequest: "Top request",
    topRequestTypesText: "These request types repeat most often across all departments.",
    problemTypesText: "These technical problems repeat most often and require technician attention.",
    requestRoomsText: "Rooms with the highest total number of requests, not only technical issues.",
    problemRoomText: "Rooms with the highest number of technical problems that require technician attention.",
    problemType: "Problem type",
    exportCsv: "Download CSV",
    exportExcel: "Download Excel",
    metric: "Metric",
    value: "Value",
    requestType: "Request type",
    topIssueCount: "Top issue count",
    problemRoomCount: "Most problematic room count",
    totalRequests: "Total requests",
    totalIssues: "Total issues",
    completedRequests: "Completed requests",
    completedIssues: "Completed issues",
    reportDetails: "Report details",
    reportDetailsIntro: "Click any card, row or metric to open the detailed list below.",
    reportDetailsEmpty: "No items for this report detail.",
    closeDetails: "Close details",
    soundAlertsLabel: "New request sound",
    alertSoundOn: "Sound is on",
    alertSoundOff: "Sound is off",
  },
  de: {
    guestHub: "GuestHub",
    staffHub: "Mitarbeiter-Hub",
    simpleOperationalView: "Einfacher operativer Überblick für das Hotelteam",
    department: "Abteilung",
    housekeeping: "Housekeeping",
    maintenance: "Technik",
    reception: "Rezeption",
    restaurant: "Restaurant",
    managerDashboard: "Manager-Dashboard",
    staffHubModules: "Module für Mitarbeiter",
    staffHubIntro:
      "Dies ist der interne GuestHub-Bereich für Mitarbeiter. Die Oberfläche bleibt bewusst einfach: klare Aufgabenlisten, gut lesbare Karten und schnelle Aktionen.",
    housekeepingDesc:
      "Gemeinsame Gästewünsche wie Handtücher, Toilettenpapier, Kissen, Decken, Bügeleisen und Minibar-Nachfüllung.",
    maintenanceDesc:
      "Technische Probleme wie Klimaanlage, Warmwasser, Beleuchtung und andere Störungen.",
    receptionDesc:
      "Überblick über alle Abteilungsanfragen und Bearbeitung der Rezeptionsanfragen.",
    managerDesc:
      "Voller operativer Überblick über Abteilungen, Status und Auslastung.",
    departmentBadge: "Abteilung",
    controlBadge: "Kontrolle",
    managementBadge: "Management",
    openArrow: "Öffnen →",
    confirmedProductDecisions: "Bestätigte Produktentscheidungen",
    confirmedDecision1:
      "Gästeanfragen umfassen nur optionale Services und optionale Wünsche, nicht die Standard-Zimmerreinigung.",
    confirmedDecision2:
      "Pflichtprozesse wie Zimmerreinigung gehören nicht zum Guest-Request-Flow.",
    confirmedDecision3:
      "Die Rezeption überwacht alle Anfragen, während die Abteilungen ihre eigenen Aufgaben bearbeiten.",
    confirmedDecision4: "Der Mitarbeiterfluss bleibt einfach: Start, Fertig, Zurück.",
    sharedHousekeepingBoard: "Gemeinsames Housekeeping-Board",
    unlockSupervisorActions: "Supervisor-Aktionen entsperren",
    lockSupervisorMode: "Supervisor-Modus sperren",
    supervisorPinRequired: "Supervisor-PIN erforderlich, um Housekeeping-Anfragen zu ändern.",
    incorrectPin: "Falscher PIN.",
    housekeepingIntro:
      "Gemeinsames Supervisor-Board nur für optionale Gästewünsche. Kein Standard-Workflow für Zimmerreinigung.",
    maintenanceIntro:
      "Nur technische Gästethemen. Klare Zimmernummer, klares Problem und einfache Statusaktionen.",
    receptionIntro:
      "Operative Kontrollansicht. Die Rezeption bearbeitet nur eigene Aufgaben und überwacht die anderen Abteilungen im Nur-Lesen-Modus.",
    managerIntro:
      "Voller operativer Überblick über alle Abteilungen. Fokus auf aktive Last, zurückgesendete Anfragen und die ältesten offenen Punkte.",
    controlCenterMonitoring: "Kontrollzentrum + Monitoring",
    technicalQueue: "Aktive technische Warteschlange",
    allDepartmentsOverview: "Überblick über alle Abteilungen",
    total: "Gesamt",
    active: "Aktiv",
    new: "Neu",
    inProgress: "In Bearbeitung",
    completed: "Erledigt",
    returned: "Zurückgegeben",
    receptionOpen: "Offen für Rezeption",
    otherDepartmentsOpen: "Offen in anderen Abteilungen",
    activeOnly: "Aktiv + zurückgegeben",
    receptionActions: "Rezeptionsaktionen",
    receptionActionsText: "Diese Anfragen können direkt von der Rezeption bearbeitet werden.",
    monitoringOnly: "Nur Überwachung",
    monitoringOnlyText:
      "Die Rezeption kann diese Anfragen überwachen, die Ausführung bleibt aber in der zuständigen Abteilung.",
    noReceptionRequests: "Keine Rezeptionsanfragen im aktuellen Filter.",
    noMonitoringRequests: "Keine Monitoring-Anfragen im aktuellen Filter.",
    oldestActiveRequests: "Älteste aktive Anfragen",
    oldestActiveRequestsText: "Diese offenen Anfragen warten bereits am längsten.",
    noActiveRequests: "Im Moment gibt es keine aktiven Anfragen.",
    filteredRequestView: "Gefilterte Anfragenansicht",
    filteredRequestViewText: "Abteilungsübergreifende Sicht für operative Nachverfolgung.",
    noRequestsForFilter: "Keine Anfragen für den aktuellen Filter.",
    departmentFilter: "Abteilungsfilter",
    statusFilter: "Statusfilter",
    sort: "Sortierung",
    priority: "Priorität",
    newest: "Neueste",
    oldest: "Älteste",
    all: "Alle",
    activeSummaryOnly: "Für diese Abteilung werden nur aktive und zurückgegebene Anfragen angezeigt.",
    allStaffCanMonitor: "Alle Housekeeping-Mitarbeiter können neue Anfragen sehen. Statusänderungen benötigen den Supervisor-PIN.",
    room: "Zimmer",
    requestedAt: "Angefragt um",
    serviceTimeNow: "Jetzt",
    serviceTimeTomorrow: "Morgen",
    serviceTimeToday: "Heute",
    managerViewOnly: "Nur Manager-Ansicht. Operative Sicht über alle Abteilungen.",
    receptionMonitoringOnly: "Nur Monitoring durch die Rezeption. Die Ausführung erfolgt in der zuständigen Abteilung.",
    start: "START",
    done: "ERLEDIGT",
    return: "ZURÜCK",
    noActionsAvailable: "Keine Aktionen verfügbar",
    reports: "Berichte",
    reportsIntro:
      "Die Managementansicht zeigt, welche Anfragearten sich am häufigsten wiederholen und welche Zimmer die meisten Probleme erzeugen.",
    reportSnapshot: "Schnellüberblick",
    topRequestTypes: "Häufigste Anfragearten",
    problematicRooms: "Problematischste Zimmer",
    problematicRoomsText: "Zimmer mit den meisten Anfragen, offenen Fällen und zurückgegebenen Problemen.",
    roomIssueBreakdown: "Aufschlüsselung nach Zimmer",
    roomIssueBreakdownText: "Zeigt, welche Probleme sich im selben Zimmer wiederholen.",
    requestCount: "Anzahl",
    returnedIssues: "Zurückgegebene Probleme",
    openIssues: "Offene Probleme",
    topIssue: "Häufigstes Problem",
    problemRoom: "Problematischstes Zimmer",
    problemRequests: "Problem-Anfragen",
    activeRooms: "Zimmer mit offenen Problemen",
    noReportData: "Noch nicht genug Daten für Berichte vorhanden.",
    noProblemData: "Keine Problemdaten verfügbar.",
    noRequestData: "Keine Anfragedaten verfügbar.",
    issueMix: "Häufigste Probleme in diesem Zimmer",
    reportsCompactLabel: "Organisierte Berichte",
    reportsCompactIntro: "Wähle einen separaten Bericht für alle Anfragen oder nur für technische Probleme und lade ihn als CSV oder Excel herunter.",
    requestsSnapshot: "Anfragen: Schnellübersicht",
    requestHeavyRooms: "Zimmer mit den meisten Anfragen",
    problemsSnapshot: "Probleme: Schnellübersicht",
    topProblemTypes: "Häufigste Probleme",
    openRequests: "Offene Anfragen",
    returnedRequests: "Zurückgegebene Anfragen",
    openRequestsText: "Anfragen, die noch nicht abgeschlossen sind.",
    returnedRequestsText: "Anfragen, die zur erneuten Bearbeitung zurückgegeben wurden.",
    openIssuesText: "Technische Probleme, die noch nicht abgeschlossen sind.",
    returnedIssuesText: "Technische Probleme, die zur erneuten Bearbeitung zurückgegeben wurden.",
    requestHeavyRoom: "Zimmer mit den meisten Anfragen",
    requestHeavyRoomCount: "Anzahl für das Zimmer mit den meisten Anfragen",
    roomsWithOpenRequests: "Zimmer mit offenen Anfragen",
    topRequest: "Häufigste Anfrage",
    topRequestTypesText: "Diese Anfragetypen treten abteilungsübergreifend am häufigsten auf.",
    problemTypesText: "Diese technischen Probleme treten am häufigsten auf und benötigen einen Techniker.",
    requestRoomsText: "Zimmer mit den meisten Anfragen insgesamt, nicht nur technischen Problemen.",
    problemRoomText: "Zimmer mit den meisten technischen Problemen, die einen Techniker benötigen.",
    problemType: "Problemtyp",
    exportCsv: "CSV herunterladen",
    exportExcel: "Excel herunterladen",
    metric: "Kennzahl",
    value: "Wert",
    requestType: "Anfragetyp",
    topIssueCount: "Anzahl häufigstes Problem",
    problemRoomCount: "Anzahl problematischstes Zimmer",
    totalRequests: "Gesamtanfragen",
    totalIssues: "Gesamtprobleme",
    completedRequests: "Erledigte Anfragen",
    completedIssues: "Erledigte Probleme",
    reportDetails: "Berichtsdetails",
    reportDetailsIntro: "Klicke auf Karte, Zeile oder Kennzahl, um unten die detaillierte Liste zu öffnen.",
    reportDetailsEmpty: "Keine Einträge für dieses Berichtsdetail.",
    closeDetails: "Details schließen",
    soundAlertsLabel: "Ton für neue Anfragen",
    alertSoundOn: "Ton ist an",
    alertSoundOff: "Ton ist aus",
  },
} as const;

const requestTypeCopy: Record<StaffUiLang, Partial<Record<StaffRequestType, string>>> = {
  bg: {
    towels: "Хавлии",
    toilet_paper: "Тоалетна хартия",
    extra_pillow: "Допълнителна възглавница",
    extra_blanket: "Допълнително одеяло",
    bathrobe: "Халат",
    slippers: "Чехли",
    baby_cot: "Бебешко легло",
    air_conditioning: "Проблем с климатика",
    light_not_working: "Осветлението не работи",
    no_hot_water: "Няма топла вода",
    tv_issue: "Проблем с телевизора",
    bathroom_issue: "Проблем в банята",
    other_technical_issue: "Друг технически проблем",
    taxi: "Такси",
    late_checkout: "Късен чек-аут",
    wake_up_call: "Събуждане",
    information: "Информация",
    restaurant_reservation: "Резервация за ресторант",
    iron: "Ютия",
    minibar: "Минибар",
    laundry: "Пране",
    other_housekeeping: "Друго за камериерки",
    luggage_help: "Помощ с багаж",
    information_request: "Информация",
    reservation_help: "Помощ с резервация",
    other_reception: "Друго за рецепция",
    door_lock_issue: "Проблем с бравата",
    wifi_issue: "Проблем с Wi‑Fi",
    power_outlet_issue: "Проблем с контакта",
    safe_issue: "Проблем със сейфа",
    balcony_door_issue: "Проблем с балконската врата",
    minibar_not_cooling: "Минибарът не охлажда",
    massage_booking: "Масаж / релакс терапия",
  },
  en: {
    towels: "Towels",
    toilet_paper: "Toilet paper",
    extra_pillow: "Extra pillow",
    extra_blanket: "Extra blanket",
    bathrobe: "Bathrobe",
    slippers: "Slippers",
    baby_cot: "Baby cot",
    air_conditioning: "Air conditioning issue",
    light_not_working: "Light not working",
    no_hot_water: "No hot water",
    tv_issue: "TV issue",
    bathroom_issue: "Bathroom issue",
    other_technical_issue: "Other technical issue",
    taxi: "Taxi",
    late_checkout: "Late checkout",
    wake_up_call: "Wake-up call",
    information: "Information",
    restaurant_reservation: "Restaurant reservation",
    iron: "Iron",
    minibar: "Minibar",
    laundry: "Laundry",
    other_housekeeping: "Other housekeeping",
    luggage_help: "Luggage help",
    information_request: "Information",
    reservation_help: "Reservation help",
    other_reception: "Other reception request",
    door_lock_issue: "Door lock issue",
    wifi_issue: "Wi‑Fi issue",
    power_outlet_issue: "Power outlet issue",
    safe_issue: "Safe issue",
    balcony_door_issue: "Balcony door issue",
    minibar_not_cooling: "Minibar not cooling",
    massage_booking: "Massage / relaxation therapy",
  },
  de: {
    towels: "Handtücher",
    toilet_paper: "Toilettenpapier",
    extra_pillow: "Zusätzliches Kissen",
    extra_blanket: "Zusätzliche Decke",
    bathrobe: "Bademantel",
    slippers: "Hausschuhe",
    baby_cot: "Babybett",
    air_conditioning: "Klimaanlagenproblem",
    light_not_working: "Licht funktioniert nicht",
    no_hot_water: "Kein Warmwasser",
    tv_issue: "Fernsehproblem",
    bathroom_issue: "Badezimmerproblem",
    other_technical_issue: "Sonstiges technisches Problem",
    taxi: "Taxi",
    late_checkout: "Später Check-out",
    wake_up_call: "Weckruf",
    information: "Information",
    restaurant_reservation: "Restaurantreservierung",
    iron: "Bügeleisen",
    minibar: "Minibar",
    laundry: "Wäsche",
    other_housekeeping: "Sonstiges Housekeeping",
    luggage_help: "Gepäckhilfe",
    information_request: "Information",
    reservation_help: "Hilfe bei Reservierung",
    other_reception: "Sonstige Rezeption-Anfrage",
    door_lock_issue: "Problem mit Türschloss",
    wifi_issue: "WLAN-Problem",
    power_outlet_issue: "Problem mit Steckdose",
    safe_issue: "Problem mit Safe",
    balcony_door_issue: "Problem mit Balkontür",
    minibar_not_cooling: "Minibar kühlt nicht",
    massage_booking: "Massage / Entspannungstherapie",
  },
};

export function staffText(lang: StaffUiLang) {
  return copy[lang] ?? copy.bg;
}

export function translateStaffStatus(status: StaffRequestStatus, lang: StaffUiLang) {
  const t = staffText(lang);
  switch (status) {
    case "new":
      return t.new;
    case "in_progress":
      return t.inProgress;
    case "completed":
      return t.completed;
    case "returned":
      return t.returned;
  }
}

export function translateStaffServiceTime(
  serviceTime: StaffServiceTime,
  lang: StaffUiLang
) {
  const t = staffText(lang);
  switch (serviceTime) {
    case "today":
      return t.serviceTimeToday;
    case "tomorrow":
      return t.serviceTimeTomorrow;
    default:
      return t.serviceTimeNow;
  }
}

export function translateDepartment(department: StaffDepartment, lang: StaffUiLang) {
  const t = staffText(lang);
  switch (department) {
    case "housekeeping":
      return t.housekeeping;
    case "maintenance":
      return t.maintenance;
    case "reception":
      return t.reception;
    case "restaurant":
      return t.restaurant;
  }
}

export function translateRequestType(
  type: StaffRequestType,
  lang: StaffUiLang,
  fallback?: string
) {
  return requestTypeCopy[lang]?.[type] ?? fallback ?? type.replace(/_/g, " ");
}
