begin;

create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  slug text not null,
  display_name text not null,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint organizations_slug_format_check
    check (slug = lower(slug) and slug ~ '^[a-z0-9][a-z0-9-]{1,62}[a-z0-9]$'),
  constraint organizations_status_check
    check (status in ('active', 'suspended', 'archived')),
  constraint organizations_slug_key unique (slug)
);

create table if not exists public.properties (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  property_key text not null,
  display_name text not null,
  country_code text null,
  lifecycle_state text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint properties_key_format_check
    check (property_key = lower(property_key) and property_key ~ '^[a-z0-9][a-z0-9-]{1,62}[a-z0-9]$'),
  constraint properties_lifecycle_state_check
    check (lifecycle_state in ('draft', 'pilot', 'active', 'suspended', 'archived')),
  constraint properties_org_key_unique unique (organization_id, property_key)
);

create index if not exists properties_organization_id_idx
  on public.properties (organization_id, lifecycle_state, property_key);

create table if not exists public.property_environments (
  id uuid primary key default gen_random_uuid(),
  property_id uuid not null references public.properties(id) on delete cascade,
  hotel_id uuid not null references public.hotels(id) on delete restrict,
  environment text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint property_environments_environment_check
    check (environment in ('production', 'sandbox', 'demo')),
  constraint property_environments_hotel_unique unique (hotel_id),
  constraint property_environments_property_environment_unique unique (property_id, environment)
);

create index if not exists property_environments_property_id_idx
  on public.property_environments (property_id, environment);

create table if not exists public.platform_admins (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  email_snapshot text null,
  role text not null default 'read_only',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint platform_admins_role_check
    check (role in ('super_admin', 'operator', 'support', 'read_only')),
  constraint platform_admins_auth_user_unique unique (auth_user_id)
);

create table if not exists public.control_plane_audit_log (
  id bigint generated by default as identity primary key,
  actor_admin_id uuid null references public.platform_admins(id) on delete set null,
  organization_id uuid null references public.organizations(id) on delete set null,
  property_id uuid null references public.properties(id) on delete set null,
  hotel_id uuid null references public.hotels(id) on delete set null,
  action text not null,
  resource_type text not null,
  resource_id text null,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint control_plane_audit_action_nonempty check (length(btrim(action)) > 0),
  constraint control_plane_audit_resource_type_nonempty check (length(btrim(resource_type)) > 0)
);

create index if not exists control_plane_audit_log_created_idx
  on public.control_plane_audit_log (created_at desc);
create index if not exists control_plane_audit_log_property_idx
  on public.control_plane_audit_log (property_id, created_at desc)
  where property_id is not null;

alter table public.organizations enable row level security;
alter table public.properties enable row level security;
alter table public.property_environments enable row level security;
alter table public.platform_admins enable row level security;
alter table public.control_plane_audit_log enable row level security;

revoke all on table public.organizations from anon, authenticated;
revoke all on table public.properties from anon, authenticated;
revoke all on table public.property_environments from anon, authenticated;
revoke all on table public.platform_admins from anon, authenticated;
revoke all on table public.control_plane_audit_log from anon, authenticated;

grant select, insert, update, delete on table public.organizations to service_role;
grant select, insert, update, delete on table public.properties to service_role;
grant select, insert, update, delete on table public.property_environments to service_role;
grant select, insert, update, delete on table public.platform_admins to service_role;
grant select, insert on table public.control_plane_audit_log to service_role;

grant usage, select on sequence public.control_plane_audit_log_id_seq to service_role;

insert into public.organizations (slug, display_name, status)
values ('stayhub-internal', 'StayHub Internal', 'active')
on conflict (slug) do update
set display_name = excluded.display_name,
    updated_at = now();

with internal_org as (
  select id
  from public.organizations
  where slug = 'stayhub-internal'
), roots as (
  select
    h.id as root_hotel_id,
    lower(coalesce(nullif(btrim(h.public_slug), ''), h.slug)) as property_key,
    h.name as display_name,
    case
      when h.country is null or btrim(h.country) = '' then null
      when length(btrim(h.country)) = 2 then upper(btrim(h.country))
      else null
    end as country_code,
    case
      when h.is_demo then 'pilot'
      when h.is_sandbox then 'pilot'
      else 'active'
    end as lifecycle_state
  from public.hotels h
  where h.production_hotel_id is null
)
insert into public.properties (
  organization_id,
  property_key,
  display_name,
  country_code,
  lifecycle_state
)
select
  internal_org.id,
  roots.property_key,
  roots.display_name,
  roots.country_code,
  roots.lifecycle_state
from internal_org
cross join roots
on conflict (organization_id, property_key) do update
set display_name = excluded.display_name,
    country_code = coalesce(excluded.country_code, public.properties.country_code),
    updated_at = now();

with internal_org as (
  select id
  from public.organizations
  where slug = 'stayhub-internal'
), hotel_roots as (
  select
    h.id as hotel_id,
    root.id as root_hotel_id,
    lower(coalesce(nullif(btrim(root.public_slug), ''), root.slug)) as property_key,
    case
      when h.is_demo then 'demo'
      when h.is_sandbox then 'sandbox'
      else 'production'
    end as environment
  from public.hotels h
  join public.hotels root
    on root.id = coalesce(h.production_hotel_id, h.id)
)
insert into public.property_environments (property_id, hotel_id, environment)
select
  p.id,
  hotel_roots.hotel_id,
  hotel_roots.environment
from hotel_roots
join internal_org on true
join public.properties p
  on p.organization_id = internal_org.id
 and p.property_key = hotel_roots.property_key
on conflict (hotel_id) do update
set property_id = excluded.property_id,
    environment = excluded.environment,
    updated_at = now();

commit;
